### ISSUE TITLE
29 - Web History Bug

### ISSUE THREAD

**Issue by melvinperello** [gretheleinstein/cictwebportal#21]
does not show the history of the student even though there is already an evaluation history in the records

please refer to the video

[Click Here to see the video](https://mega.nz/#!8jYAVZwK!aU_ygJRKHDuQrVYPyUHXtbuHbPAVAC33KL1q3DT_vVo)

**Comment by gretheleinstein** [comment]
Ok na to.. nakalimutan ko ibalik ung active = 0 sa 1. Tinatry ko kasi pag wala
