### ISSUE TITLE
30 - Default Grade Selection

### ISSUE THREAD

**Issue by melvinperello** [gretheleinstein/cictwebportal#22]
On the grade tab when there is already an entry select the latest as the default

refer to the video for more details
[Video Link](https://mega.nz/#!ZnhBEZgB!eP9M2T8gg2fl6NhDDvXIRcqMXZHTmF4OEQdrKobTcsA)

**Comment by gretheleinstein** [comment]
Di ko na napanuod ung video.. pero kung ung kagaya nung sa bulsu yun. Yun ung ginawa ko..

**Comment by melvinperello** [comment]
bakit di mo napanood nadodownload yong video

**Comment by gretheleinstein** [comment]
umaga na nun e. tutulog pa ko. ngaun ko pa lang papanuorin..
