### ISSUE TITLE
Uploading Profile Picture Error

### ISSUE THREAD

**Issue by melvinperello** [gretheleinstein/cictwebportal#9]
> The error occurs when the student has already an account but no entry in the **student_profile** table

How to reproduce the error

1. Create a student
2. Create an account
3. Login then delete the entry of the student from the **student_profile** table
4. Now try to upload the photo.

The student should be able to upload a photo and create a student_profile entry with blank fields blank means empty not null

**Comment by gretheleinstein** [comment]
Di ko maintindahan kung bakit ko kailangan delete ung entry nya sa student_profile

**Comment by gretheleinstein** [comment]
The student should be able to upload a photo and create a student_profile entry with blank fields blank means empty not null - kelan ba to mangyayari...

**Comment by melvinperello** [comment]
Burahin mo yung entry sa studenr profile sa db nung student tsaka ka magupload

**Comment by gretheleinstein** [comment]
Edi di ako makakapagupload. Wala na ko paglalagyan e.

**Comment by gretheleinstein** [comment]
Ganito ba? Pag pasok ko ng login. Dapat icheck kung may student_profile na ung student pag wala. magcreate ng student_profile dun sa code?

**Comment by melvinperello** [comment]
iredirect mo siya sa page na Oops cannot upload your photo somethings missing with your profile please select your cluster assignment

tapos magkakaprofile na siya ka siya makakapag upload
